"""Initial migration

Revision ID: c122e21c19c4
Revises: 77830e1e9685
Create Date: 2024-01-21 10:29:03.930475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c122e21c19c4'
down_revision = '77830e1e9685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
